# Generated by Django 5.0.1 on 2024-01-26 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_product', to='app_cook.dishes'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_product', to='app_cook.products'),
        ),
    ]
